import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'

const Home: NextPage = ({collection}) => {
  console.log(collection.length);

  return (
    <div>
      <Head>
        <title>Mark&apos;s Discogs Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <style jsx>{`
          .collection-item {
            perspective: 1000px;
          }

          .collection-item__inner {
            transform-style: preserve-3d;
          }

          .collection-item:hover .collection-item__inner {
            transform: rotateY(180deg);
          }

          .collection-item__front,
          .collection-item__back {
            backface-visibility: hidden;
          }

          .collection-item__back {
            transform: rotateY(180deg);
          }
        `}</style>
        <div className='collection flex flex-wrap'>
          {collection.map(function(release, i){
            return (
              <div className='collection-item w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/6 aspect-square' key={i}>
                <div className='collection-item__inner relative w-full h-full text-center transition-transform ease-linear duration-500'>
                  <div className='collection-item__front absolute w-full h-full'>
                    <p>{release.basic_information.cover_image}</p>
                    <Image src={release.basic_information.cover_image} layout="fill" className="aspect-square" alt="Album artwork" />
                  </div>
                  <div className='collection-item__back absolute w-full h-full bg-black text-white'>
                    <h2>{release.basic_information.title} by {release.basic_information.artists[0].name}</h2>
                    <Link href={`/release/${release.id}`}>View release</Link>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
        {/* {collection.pagination.items} */}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  // Call an Discogs API endpoint to get my collection.
  const token = process.env.DISCOGS_API_TOKEN
  const resUrl = `https://api.discogs.com/users/mweston/collection/folders/0/releases?&per_page=100&token=${token}`;
  const res = await fetch(resUrl);
  const resJson = await res.json();
  const collection = resJson.releases;

  /**
   * When there is more than one page to the collection i.e. collection larger than per_page in request
   * Loop through pages, requesting remaining collection items and merging the array of releases together
   */
  
  if(resJson.pagination.pages != 1) {
    for(let page = 2; page <= resJson.pagination.pages; page++) {
      let nextPageRes = await fetch(resJson.pagination.urls.next);
      let nextPageCollection = await nextPageRes.json();
      collection.push(...nextPageCollection.releases);
    }
  }
  // Return collection to Home component
  return {
    props: {
      collection,
    },
  }
}

export default Home
